import React from "react";
import "./App.css";
import IncidentTable from "./components/IncidentTable";
import LogAnalyzer from "./components/LogAnalyzer";

export default function App() {
  return (
    <main className="app-shell">
      <section className="hero">
        <h1>AI Ops Automation System</h1>
        <p>
          Intelligent incident analysis and automation dashboard
        </p>
      </section>

      <section className="panel-grid">
        <article className="panel">
          <h2>Dashboard</h2>
          <p>
            View the latest incidents generated by the backend analysis and
            automation workflow.
          </p>
          <IncidentTable />
        </article>

        <article className="panel">
          <h2>Analyze Logs</h2>
          <p>
            Paste application logs and send them to the backend for incident
            analysis and automation metadata generation.
          </p>
          <LogAnalyzer />
        </article>
      </section>
    </main>
  );
}
